# Generated by Django 4.1.4 on 2022-12-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=100)),
                ('ar_pic', models.ImageField(upload_to='')),
                ('ar_text', models.TextField()),
                ('ar_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_text', models.TextField(max_length=1000)),
                ('com_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.article')),
            ],
        ),
    ]
