# Generated by Django 4.1.4 on 2022-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_article_ar_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ar_com',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='com_name',
            field=models.CharField(default='No Name', max_length=20),
        ),
    ]
