# Generated by Django 4.1.4 on 2022-12-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_article_ar_com_comments_com_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='com_to',
            field=models.IntegerField(),
        ),
    ]
